# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "8"
sudo: required

### TODO: sign osx application
### TODO: sign win application
### TODO: build/sign learnLang-ios
### TODO: build learnLang-winphone
### TODO: get version numbers from main package.json to installation info (or create from tags or???)
matrix:
  include:
    #### learnLang: #####################
    #- os: linux
    #  env: JB=010 TOS=android   APP=learnLang FRM=cordova OPT2=Small
    - os: linux
      env: JB=020 TOS=android   APP=learnLang FRM=cordova OPT2=Small    DEBUGV=yes
    #- os: linux
    #  env: JB=030 TOS=android   APP=learnLang FRM=cordova
    #- os: linux
    #  env: JB=040 TOS=android   APP=learnLang FRM=cordova               DEBUGV=yes
    #- os: linux
    #  env: JB=050 TOS=linux-win APP=learnLang FRM=nwjs
    #- os: linux
    #  env: JB=060 TOS=linux-win APP=learnLang FRM=nwjs                  DEBUGV=yes
    #- os: osx
    #  env: JB=070 TOS=osx       APP=learnLang FRM=nwjs
    ##-os: osx
    ## env: JB=080 TOS=osx       APP=learnLang FRM=nwjs                  DEBUGV=yes
    #### puzzle15: ######################
    #- os: linux
    #  env: JB=090 TOS=android   APP=puzzle15  FRM=cordova-ionic
    ##-os: linux
    ## env: JB=100 TOS=android   APP=puzzle15  FRM=cordova-ionic         DEBUGV=yes
    ##-os: linux
    ## env: JB=110 TOS=linux-win APP=puzzle15  FRM=nwjs-ionic
    ##-os: linux
    ## env: JB=120 TOS=linux-win APP=puzzle15  FRM=nwjs-ionic            DEBUGV=yes
    ##-os: linux
    ## env: JB=130 TOS=osx       APP=puzzle15  FRM=nwjs-ionic
    ##-os: linux
    ## env: JB=140 TOS=osx       APP=puzzle15  FRM=nwjs-ionic            DEBUGV=yes
    #### tripSave: ######################
    ##-os: linux
    ## env: JB=150 TOS=android   APP=tripSave  FRM=nwjs
    ##-os: linux
    ## env: JB=160 TOS=android   APP=tripSave  FRM=nwjs                  DEBUGV=yes
    ##-os: linux
    ## env: JB=170 TOS=linux-win APP=tripSave  FRM=nwjs
    ##-os: linux
    ## env: JB=180 TOS=linux-win APP=tripSave  FRM=nwjs                  DEBUGV=yes
    ##-os: linux
    ## env: JB=190 TOS=osx       APP=tripSave  FRM=nwjs
    ##-os: linux
    ## env: JB=200 TOS=osx       APP=tripSave  FRM=nwjs                  DEBUGV=yes

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 20

# cache: ### caching can be slower than not caching (if many folders)
#     timeout: 300 # (5*60 s = 5 min)
#     directories:
#     - $NVM_DIR # $(npm config get prefix)
#     - _tmp_cached/android-sdk-linux
#     - apps/$APP/node_modules
#     - apps/$APP/platforms
#     - apps/$APP/plugins

before_script:
    - export APPNAME=$APP$OPT2
    - export TARGET_OS=$TOS
    - export WORK_DIR=$PWD
    - export APPL_DIR=$WORK_DIR/apps/$APP
    - export RELEASES_DIR=$WORK_DIR/releases
    - export CLONE_DIR=$WORK_DIR/_tmp/mobileApps
    #-export  CXX=g++-4.8 #needed for android???
    - export  ANDROID_MANIFEST=$APPL_DIR/platforms/android/AndroidManifest.xml
    - export  ANDROID_HOME1=$WORK_DIR/_tmp_cached
    - export  ANDROID_HOME=$WORK_DIR/_tmp_cached/android-sdk-linux
    - export  ABTVF=26.0.2
    - export  ZIPALIGN=$ANDROID_HOME/build-tools/$ABTVF/zipalign

    - . $WORK_DIR/scripts/_mydo.sh
    - . $WORK_DIR/scripts/common_before_install.sh
    - . $APPL_DIR/scripts/before_install.sh
    - . $APPL_DIR/scripts/copy.sh
    - . $APPL_DIR/scripts/install.sh

    - mkdir gradle341
    - pushd gradle341
    - wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
    - sudo unzip -d /opt/gradle gradle-3.4.1-bin.zip
    - export PATH=$PWD:$PATH ### :/opt/gradle/gradle-3.4.1/bin
    - popd

    - . $APPL_DIR/scripts/build.sh

script:
    - ls -lh $RELEASES_DIR || echo 1

after_success:
    - . $WORK_DIR/scripts/deploy_github_releases.sh
    # - . $WORK_DIR/scripts/deploy_heroku.sh
