# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "8"
sudo: false

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - openjdk-7-jdk
        - lib32stdc++6
        - lib32z1
        - wine
        - nsis
        # - wine1.6

env:
    global:
        - CXX=g++-4.8
        - HOME_DIR=$PWD
        - ANDROID_HOME=$HOME_DIR/android-sdk-linux
        - ZIPALIGN=$ANDROID_HOME/build-tools/26.0.1/zipalign
        - RELEASES_DIR=$HOME_DIR/releases
        - CLONE_DIR=$HOME_DIR/_tmp/mobileApps
    matrix:
        # - JOBNAME=learnLangDebug     APP=learnLang PLAT=android OPT1=debug
        # - JOBNAME=learnLangFullDebug APP=learnLang PLAT=android OPT1=debug OPT2=Full
        - JOBNAME=learnLang          APP=learnLang PLAT=android OPT1=release
        - JOBNAME=learnLangFull      APP=learnLang PLAT=android OPT1=release OPT2=Full EXTRASTEP=deploy
        - JOBNAME=learnLangDeskFull  APP=learnLang PLAT=desktop OPT1=release OPT2=Full
        # - JOBNAME=puzzle15Debug      APP=puzzle15  PLAT=android OPT1=debug
        - JOBNAME=puzzle15           APP=puzzle15  PLAT=android OPT1=release
        # - JOBNAME=tripSaveDebug      APP=tripSave PLAT=android OPT1=debug
        # - JOBNAME=tripSaveRelease    APP=tripSave PLAT=android OPT1=release

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 20

cache:
    timeout: 300 # (5*60 s = 5 min)
    directories:
    - $NVM_DIR # $(npm config get prefix)
    - android-sdk-linux
    - apps/$APP/node_modules
    - apps/$APP/platforms
    - apps/$APP/plugins

before_install:
    ### Environment 2:
    - export APPNAME=$APP$OPT2
    - export APP_DIR=$HOME_DIR/apps/$APP
    - export ANDROID_MANIFEST=$APP_DIR/platforms/android/AndroidManifest.xml

    - cd apps/$APP
    - npm install -g npm
    - source ./scripts/before_install.sh

install:
    - source ./scripts/copy.sh
    - source ./scripts/install.sh
    - source $HOME_DIR/scripts/android_check_permissions.sh

before_script:
    - source ./scripts/build.sh
    - source $HOME_DIR/scripts/android_check_permissions.sh

script:
    - ls -lh $RELEASES_DIR || echo 1

after_success:
    - cd $HOME_DIR
    - source $HOME_DIR/scripts/deploy_github_releases.sh
    # - source $HOME_DIR/scripts/deploy_heroku.sh
