# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "6"
sudo: false

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - openjdk-7-jdk
        - lib32stdc++6
        - lib32z1

env:
    global:
        - CXX=g++-4.8
        - ANDROID_HOME=$TRAVIS_BUILD_DIR/android-sdk-linux
        - zipalign=$ANDROID_HOME/build-tools/26.0.1/zipalign
    matrix:
        - JOBNAME=learnLangDebug     BDIR=learnLang BOPT1=debug
        - JOBNAME=learnLangFullDebug BDIR=learnLang BOPT1=debug BOPT2=full
        # - JOBNAME=tripSaveDebug      BDIR=tripSave BOPT1=debug
        # - JOBNAME=tripSaveRelease    BDIR=tripSave BOPT1=release

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 3

cache:
    timeout: 300 # (5*60 s = 5 min)
    directories:
    - $NVM_DIR # $(npm config get prefix)
    - android-sdk-linux
    - $BDIR/node_modules
    - learnLang/node_modules
    - learnLang/platforms
    - learnLang/plugins

before_install:
    - source ./s/android_sdk_install.sh
    - npm install -g npm
    - node --version
    - npm --version
    - pwd
    - npm install -g gulp bower cordova ionic

install:
    - pwd
    - cd $BDIR
    - pwd
    - source ./install.sh
    # - bower update
    # - source ./s/ionic_cordova_prepare.sh

before_script:
    - pwd

script:
    - pwd
    - source ./script.sh
    # - source ./s/deploy_github_releases.sh $JOBNAME
    # - ls platforms/android/build/outputs/apk
    # - ls releases
    # - echo 1
