# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "6"
sudo: false

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - openjdk-7-jdk
        - lib32stdc++6
        - lib32z1

env:
    global:
        - CXX=g++-4.8
        - ANDROID_HOME=$TRAVIS_BUILD_DIR/android-sdk-linux
        - zipalign=$ANDROID_HOME/build-tools/26.0.1/zipalign
    matrix:
        - JOBNAME=learnLangDebug     APP=learnLang TARG=android BOPT1=debug BOPT2=""
        - JOBNAME=learnLangFullDebug APP=learnLang TARG=android BOPT1=debug BOPT2=Full
        - JOBNAME=learnLang          APP=learnLang TARG=android BOPT1=release BOPT2=""
        - JOBNAME=learnLangFull      APP=learnLang TARG=android BOPT1=release BOPT2=Full
        # - JOBNAME=tripSaveDebug      APP=tripSave TARG=android BOPT1=debug
        # - JOBNAME=tripSaveRelease    APP=tripSave TARG=android BOPT1=release

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 3

cache:
    timeout: 300 # (5*60 s = 5 min)
    directories:
    - $NVM_DIR # $(npm config get prefix)
    - android-sdk-linux
    - app-$APP/node_modules
    - app-$APP/platforms
    - app-$APP/plugins

before_install:
    - source ./server-scripts/android_sdk_install.sh
    - npm install -g npm
    - node --version
    - npm --version
    - pwd
    - npm install -g gulp bower cordova ionic

install:
    - pwd
    - cd app-$APP
    - pwd
    - source ./scripts/copy-$TARG.sh
    - source ./scripts/install-$TARG.sh
    # - bower update
    # - source ./server-scripts/ionic_cordova_prepare.sh

before_script:
    - pwd

script:
    - pwd
    - source ./scripts/build-$TARG.sh
    # - source ./server-scripts/deploy_github_releases.sh $JOBNAME
    - ls -lh platforms/android/build/outputs/apk
    - ls -lh ../releases
    - echo 1
