# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "8"
sudo: required

# addons:
#     apt:
#         sources:
#         - ubuntu-toolchain-r-test

env:
    global:
        - CXX=g++-4.8

        - WORK_DIR=$PWD
        - ANDROID_HOME=$WORK_DIR/_tmp_cached/android-sdk-linux
        - ZIPALIGN=$ANDROID_HOME/build-tools/26.0.1/zipalign
        - RELEASES_DIR=$WORK_DIR/releases
        - CLONE_DIR=$WORK_DIR/_tmp/mobileApps

### TODO: clean packaje.json from nwjs-build-phoenix staff
### TODO: remove $PLAT, replace it by $FRM/$TRG_OS
### TODO: APP-->APPL_DIR; set APPNAME here(?)
### TODO: system settings/installations/packages from addons: apt: packages: to install step
### TODO: copy version from main package.json (or create from tags or???)
matrix:
  include:
    ### learnLang:
    # - os: linux
    #   env: JOBNAME=010 APP=learnLang PLAT=android FRM=cordova TRG_OS=android   OPT1=debug
    # - os: linux
    #   env: JOBNAME=020 APP=learnLang PLAT=android FRM=cordova TRG_OS=android   OPT1=debug OPT2=Full
    - os: linux
      env: JOBNAME=030 APP=learnLang PLAT=android FRM=cordova TRG_OS=android   OPT1=release
    - os: linux
      env: JOBNAME=040 APP=learnLang PLAT=android FRM=cordova TRG_OS=android   OPT1=release OPT2=Full EXTRASTEP=deploy
    - os: linux
      env: JOBNAME=050 APP=learnLang PLAT=desktop FRM=nwjs    TRG_OS=linux-win OPT1=release OPT2=Full
    - os: osx
      env: JOBNAME=060 APP=learnLang PLAT=desktop FRM=nwjs    TRG_OS=osx       OPT1=release OPT2=Full
    ### puzzle15:
    # - os: linux
    #   env: JOBNAME=070 APP=puzzle15  PLAT=android FRM=cordova-ionic TRG_OS=android   OPT1=debug
    - os: linux
      env: JOBNAME=080 APP=puzzle15  PLAT=android FRM=cordova-ionic TRG_OS=android   OPT1=release
    ### tripSave:
    # - os: linux
    #   env: JOBNAME=090 APP=tripSave  PLAT=android FRM=cordova TRG_OS=android   OPT1=debug
    # - os: linux
    #   env: JOBNAME=100 APP=tripSave  PLAT=android FRM=cordova TRG_OS=android   OPT1=release

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 20

# cache:
#     timeout: 300 # (5*60 s = 5 min)
#     directories:
#     - $NVM_DIR # $(npm config get prefix)
#     - _tmp_cached/android-sdk-linux
#     - apps/$APP/node_modules
#     - apps/$APP/platforms
#     - apps/$APP/plugins

before_script:
    - export APPNAME=$APP$OPT2
    - export APPL_DIR=$WORK_DIR/apps/$APP
    - export ANDROID_MANIFEST=$APPL_DIR/platforms/android/AndroidManifest.xml

    - . $WORK_DIR/scripts/common_before_install.sh
    - . $APPL_DIR/scripts/before_install.sh
    - . $APPL_DIR/scripts/copy.sh
    - . $APPL_DIR/scripts/install.sh
    - . $APPL_DIR/scripts/build.sh

script:
    - ls -lh $RELEASES_DIR || echo 1

after_success:
    - . $WORK_DIR/scripts/deploy_github_releases.sh
    # - . $WORK_DIR/scripts/deploy_heroku.sh
