# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "8"
sudo: required

env:
    global:
        - CXX=g++-4.8

        - WORK_DIR=$PWD
        - ANDROID_HOME1=$WORK_DIR/_tmp_cached
        - ANDROID_HOME=$WORK_DIR/_tmp_cached/android-sdk-linux
        - ZIPALIGN=$ANDROID_HOME/build-tools/26.0.1/zipalign
        - RELEASES_DIR=$WORK_DIR/releases
        - CLONE_DIR=$WORK_DIR/_tmp/mobileApps

### TODO: build learnLang-ios
### TODO: build learnLang-winphone
### TODO: get version numbers from main package.json to installation info (or create from tags or???)
matrix:
  include:
    ### learnLang: ###
    #-os: linux
    # env: JB=010 TOS=android   APP=learnLang FRM=cordova OPT1=debug   OPT2=Small
    #-os: linux
    # env: JB=020 TOS=android   APP=learnLang FRM=cordova OPT1=debug
    - os: linux
      env: JB=030 TOS=android   APP=learnLang FRM=cordova OPT1=release OPT2=Small
    - os: linux
      env: JB=040 TOS=android   APP=learnLang FRM=cordova OPT1=release
    - os: linux
      env: JB=050 TOS=linux-win APP=learnLang FRM=nwjs    OPT1=release
    - os: osx
      env: JB=060 TOS=osx       APP=learnLang FRM=nwjs    OPT1=release
    ### puzzle15: ###
    #-os: linux
    # env: JB=070 TOS=android   APP=puzzle15  FRM=cordova-ionic OPT1=debug
    - os: linux
      env: JB=080 TOS=android   APP=puzzle15  FRM=cordova-ionic OPT1=release
    ### tripSave: ###
    #-os: linux
    # env: JB=090 TOS=android   APP=tripSave  FRM=cordova OPT1=debug
    #-os: linux
    # env: JB=100 TOS=android   APP=tripSave  FRM=cordova OPT1=release

branches:
    only:
        - master
    except: # tags starting with vX.X.X (usually commited by travis)
        - /^v?\d+\.\d+\.\d+/

git:
    depth: 20

# cache: ### caching can be slower than not caching (if many folders)
#     timeout: 300 # (5*60 s = 5 min)
#     directories:
#     - $NVM_DIR # $(npm config get prefix)
#     - _tmp_cached/android-sdk-linux
#     - apps/$APP/node_modules
#     - apps/$APP/platforms
#     - apps/$APP/plugins

before_script:
    - export APPNAME=$APP$OPT2
    - export TARGET_OS=$TOS
    - export APPL_DIR=$WORK_DIR/apps/$APP
    - export ANDROID_MANIFEST=$APPL_DIR/platforms/android/AndroidManifest.xml

    - . $WORK_DIR/scripts/_mydo.sh
    - . $WORK_DIR/scripts/common_before_install.sh
    - . $APPL_DIR/scripts/before_install.sh
    - . $APPL_DIR/scripts/copy.sh
    - . $APPL_DIR/scripts/install.sh
    - . $APPL_DIR/scripts/build.sh

script:
    - ls -lh $RELEASES_DIR || echo 1

after_success:
    - . $WORK_DIR/scripts/deploy_github_releases.sh
    # - . $WORK_DIR/scripts/deploy_heroku.sh
