#!/usr/bin/env bash

#msg="english added, fail fixing (now android graddle needs declared flavor dimensions)"
#msg="english added, crosswalk disabled (because build fail after google gradle update)"
msg="btCtl"

# pull-n-merge
#git fetch origin && git merge --no-edit -m "[ci skip] merge with branch master"
git fetch && git pull

# add all changed files
git add -A

# commit
git commit -m "$msg"

# git push origin master
git push
